import { $Enums } from '@prisma/client';
import { prisma } from '../prismaConfig';

export async function upsertMissions() {
  const missionsArray = [
    {
      missionType: $Enums.MissonType.TIME,
      missions: [
        {
          title: 'Desafio Inicial: 30 minutos de treino',
          description: 'Acumule 30 minutos de treino',
          experiencePoints: 100,
          goal: 30,
        },
        {
          title: 'Persistência: 60 minutos de treino',
          description: 'Acumule 60 minutos de treino',
          experiencePoints: 100,
          goal: 60,
        },
        {
          title: 'Evolução Contínua: 90 minutos de treino',
          description: 'Acumule 90 minutos de treino',
          experiencePoints: 100,
          goal: 90,
        },
        {
          title: 'Hora Extra: 120 minutos de treino',
          description: 'Acumule 120 minutos de treino',
          experiencePoints: 100,
          goal: 120,
        },
        {
          title: 'Treino Intenso: 180 minutos de treino',
          description: 'Acumule 180 minutos de treino',
          experiencePoints: 150,
          goal: 180,
        },
        {
          title: 'Além dos Limites: 240 minutos de treino',
          description: 'Acumule 240 minutos de treino',
          experiencePoints: 150,
          goal: 240,
        },
        {
          title: 'Determinação Extrema: 300 minutos de treino',
          description: 'Acumule 300 minutos de treino',
          experiencePoints: 150,
          goal: 300,
        },
        {
          title: 'Força de Vontade: 360 minutos de treino',
          description: 'Acumule 360 minutos de treino',
          experiencePoints: 150,
          goal: 360,
        },
        {
          title: 'Resiliência: 420 minutos de treino',
          description: 'Acumule 420 minutos de treino',
          experiencePoints: 150,
          goal: 420,
        },
        {
          title: 'Foco Total: 480 minutos de treino',
          description: 'Acumule 480 minutos de treino',
          experiencePoints: 150,
          goal: 480,
        },
        {
          title: 'Concentração Absoluta: 540 minutos de treino',
          description: 'Acumule 540 minutos de treino',
          experiencePoints: 150,
          goal: 540,
        },
        {
          title: 'Experiência Intensa: 600 minutos de treino',
          description: 'Acumule 600 minutos de treino',
          experiencePoints: 150,
          goal: 600,
        },
        {
          title: 'Desafio Supremo: 720 minutos de treino',
          description: 'Acumule 720 minutos de treino',
          experiencePoints: 200,
          goal: 720,
        },
        {
          title: 'Poder Infinito: 840 minutos de treino',
          description: 'Acumule 840 minutos de treino',
          experiencePoints: 200,
          goal: 840,
        },
        {
          title: 'Mestre do Treino: 960 minutos de treino',
          description: 'Acumule 960 minutos de treino',
          experiencePoints: 200,
          goal: 960,
        },
        {
          title: 'Campeão do Esforço: 1080 minutos de treino',
          description: 'Acumule 1080 minutos de treino',
          experiencePoints: 200,
          goal: 1080,
        },
        {
          title: 'Superação Constante: 1200 minutos de treino',
          description: 'Acumule 1200 minutos de treino',
          experiencePoints: 200,
          goal: 1200,
        },
        {
          title: 'Treino Inesgotável: 1560 minutos de treino',
          description: 'Acumule 1560 minutos de treino',
          experiencePoints: 300,
          goal: 1560,
        },
        {
          title: 'Força Incansável: 1920 minutos de treino',
          description: 'Acumule 1920 minutos de treino',
          experiencePoints: 300,
          goal: 1920,
        },
        {
          title: 'Resistência Ilimitada: 2280 minutos de treino',
          description: 'Acumule 2280 minutos de treino',
          experiencePoints: 300,
          goal: 2280,
        },
        {
          title: 'Persistência Infinita: 2640 minutos de treino',
          description: 'Acumule 2640 minutos de treino',
          experiencePoints: 300,
          goal: 2640,
        },
        {
          title: 'Dedicação Total: 3000 minutos de treino',
          description: 'Acumule 3000 minutos de treino',
          experiencePoints: 300,
          goal: 3000,
        },
        {
          title: 'Inabalável: 5000 minutos de treino',
          description: 'Acumule 5000 minutos de treino',
          experiencePoints: 300,
          goal: 5000,
        },
        {
          title: 'Imbatível: 7000 minutos de treino',
          description: 'Acumule 7000 minutos de treino',
          experiencePoints: 300,
          goal: 7000,
        },
        {
          title: 'Indestrutível: 9000 minutos de treino',
          description: 'Acumule 9000 minutos de treino',
          experiencePoints: 300,
          goal: 9000,
        },
        {
          title: 'Invencível: 11000 minutos de treino',
          description: 'Acumule 11000 minutos de treino',
          experiencePoints: 300,
          goal: 11000,
        },
        {
          title: 'Supremacia: 13000 minutos de treino',
          description: 'Acumule 13000 minutos de treino',
          experiencePoints: 300,
          goal: 13000,
        },
        {
          title: 'Excelência: 15000 minutos de treino',
          description: 'Acumule 15000 minutos de treino',
          experiencePoints: 300,
          goal: 15000,
        },
        {
          title: 'Domínio Absoluto: 17000 minutos de treino',
          description: 'Acumule 17000 minutos de treino',
          experiencePoints: 300,
          goal: 17000,
        },
        {
          title: 'Perfeição: 19000 minutos de treino',
          description: 'Acumule 19000 minutos de treino',
          experiencePoints: 300,
          goal: 19000,
        },
        {
          title: 'Alta Performance: 21000 minutos de treino',
          description: 'Acumule 21000 minutos de treino',
          experiencePoints: 300,
          goal: 21000,
        },
        {
          title: 'Excelência Máxima: 23000 minutos de treino',
          description: 'Acumule 23000 minutos de treino',
          experiencePoints: 300,
          goal: 23000,
        },
        {
          title: 'Superação Extrema: 25000 minutos de treino',
          description: 'Acumule 25000 minutos de treino',
          experiencePoints: 300,
          goal: 25000,
        },
        {
          title: 'Conquista Imbatível: 27000 minutos de treino',
          description: 'Acumule 27000 minutos de treino',
          experiencePoints: 300,
          goal: 27000,
        },
        {
          title: 'Poder Supremo: 29000 minutos de treino',
          description: 'Acumule 29000 minutos de treino',
          experiencePoints: 300,
          goal: 29000,
        },
        {
          title: 'Perseverança Infinita: 31000 minutos de treino',
          description: 'Acumule 31000 minutos de treino',
          experiencePoints: 300,
          goal: 31000,
        },
        {
          title: 'Força Inquebrável: 33000 minutos de treino',
          description: 'Acumule 33000 minutos de treino',
          experiencePoints: 300,
          goal: 33000,
        },
        {
          title: 'Energia Inesgotável: 35000 minutos de treino',
          description: 'Acumule 35000 minutos de treino',
          experiencePoints: 300,
          goal: 35000,
        },
        {
          title: 'Resistência Inabalável: 37000 minutos de treino',
          description: 'Acumule 37000 minutos de treino',
          experiencePoints: 300,
          goal: 37000,
        },
        {
          title: 'Dedicação Infinita: 39000 minutos de treino',
          description: 'Acumule 39000 minutos de treino',
          experiencePoints: 300,
          goal: 39000,
        },
        {
          title: 'Foco Inabalável: 41000 minutos de treino',
          description: 'Acumule 41000 minutos de treino',
          experiencePoints: 300,
          goal: 41000,
        },
        {
          title: 'Conquista Absoluta: 43000 minutos de treino',
          description: 'Acumule 43000 minutos de treino',
          experiencePoints: 300,
          goal: 43000,
        },
        {
          title: 'Realização Máxima: 45000 minutos de treino',
          description: 'Acumule 45000 minutos de treino',
          experiencePoints: 300,
          goal: 45000,
        },
        {
          title: 'Alcance de Metas: 47000 minutos de treino',
          description: 'Acumule 47000 minutos de treino',
          experiencePoints: 300,
          goal: 47000,
        },
        {
          title: 'Superação Ilimitada: 49000 minutos de treino',
          description: 'Acumule 49000 minutos de treino',
          experiencePoints: 300,
          goal: 49000,
        },
        {
          title: 'Superação Absoluta: 51000 minutos de treino',
          description: 'Acumule 51000 minutos de treino',
          experiencePoints: 300,
          goal: 51000,
        },
        {
          title: 'Mestre da Superação: 53000 minutos de treino',
          description: 'Acumule 53000 minutos de treino',
          experiencePoints: 300,
          goal: 53000,
        },
        {
          title: 'Superação Inesgotável: 55000 minutos de treino',
          description: 'Acumule 55000 minutos de treino',
          experiencePoints: 300,
          goal: 55000,
        },
        {
          title: 'Superação Infinita: 57000 minutos de treino',
          description: 'Acumule 57000 minutos de treino',
          experiencePoints: 300,
          goal: 57000,
        },
        {
          title: 'Conquista Final: 59000 minutos de treino',
          description: 'Acumule 59000 minutos de treino',
          experiencePoints: 300,
          goal: 59000,
        },
        {
          title: 'Poder Supremo: 61000 minutos de treino',
          description: 'Acumule 61000 minutos de treino',
          experiencePoints: 300,
          goal: 61000,
        },
        {
          title: 'Excelência Eterna: 63000 minutos de treino',
          description: 'Acumule 63000 minutos de treino',
          experiencePoints: 300,
          goal: 63000,
        },
        {
          title: 'Domínio Absoluto: 65000 minutos de treino',
          description: 'Acumule 65000 minutos de treino',
          experiencePoints: 300,
          goal: 65000,
        },
        {
          title: 'Força Inquebrável: 67000 minutos de treino',
          description: 'Acumule 67000 minutos de treino',
          experiencePoints: 300,
          goal: 67000,
        },
        {
          title: 'Energia Ilimitada: 69000 minutos de treino',
          description: 'Acumule 69000 minutos de treino',
          experiencePoints: 300,
          goal: 69000,
        },
        {
          title: 'Superação Extrema: 71000 minutos de treino',
          description: 'Acumule 71000 minutos de treino',
          experiencePoints: 300,
          goal: 71000,
        },
        {
          title: 'Dedicação Infinita: 73000 minutos de treino',
          description: 'Acumule 73000 minutos de treino',
          experiencePoints: 300,
          goal: 73000,
        },
        {
          title: 'Resiliência Inabalável: 75000 minutos de treino',
          description: 'Acumule 75000 minutos de treino',
          experiencePoints: 300,
          goal: 75000,
        },
        {
          title: 'Foco Absoluto: 77000 minutos de treino',
          description: 'Acumule 77000 minutos de treino',
          experiencePoints: 300,
          goal: 77000,
        },
        {
          title: 'Conquista Absoluta: 79000 minutos de treino',
          description: 'Acumule 79000 minutos de treino',
          experiencePoints: 300,
          goal: 79000,
        },
        {
          title: 'Superação Total: 81000 minutos de treino',
          description: 'Acumule 81000 minutos de treino',
          experiencePoints: 300,
          goal: 81000,
        },
        {
          title: 'Realização Final: 83000 minutos de treino',
          description: 'Acumule 83000 minutos de treino',
          experiencePoints: 300,
          goal: 83000,
        },
        {
          title: 'Alcance Supremo: 85000 minutos de treino',
          description: 'Acumule 85000 minutos de treino',
          experiencePoints: 300,
          goal: 85000,
        },
        {
          title: 'Mestre da Resistência: 87000 minutos de treino',
          description: 'Acumule 87000 minutos de treino',
          experiencePoints: 300,
          goal: 87000,
        },
        {
          title: 'Superação Incansável: 89000 minutos de treino',
          description: 'Acumule 89000 minutos de treino',
          experiencePoints: 300,
          goal: 89000,
        },
        {
          title: 'Superação Ilimitada: 91000 minutos de treino',
          description: 'Acumule 91000 minutos de treino',
          experiencePoints: 300,
          goal: 91000,
        },
        {
          title: 'Conquista Suprema: 93000 minutos de treino',
          description: 'Acumule 93000 minutos de treino',
          experiencePoints: 300,
          goal: 93000,
        },
        {
          title: 'Poder Infinito: 95000 minutos de treino',
          description: 'Acumule 95000 minutos de treino',
          experiencePoints: 300,
          goal: 95000,
        },
        {
          title: 'Excelência Total: 97000 minutos de treino',
          description: 'Acumule 97000 minutos de treino',
          experiencePoints: 300,
          goal: 97000,
        },
        {
          title: 'Domínio Absoluto: 99000 minutos de treino',
          description: 'Acumule 99000 minutos de treino',
          experiencePoints: 300,
          goal: 99000,
        },
        {
          title: 'Superação Final: 100000 minutos de treino',
          description: 'Acumule 100000 minutos de treino',
          experiencePoints: 300,
          goal: 100000,
        },
      ],
    },
    {
      missionType: $Enums.MissonType.WORKOUT_TYPE,
      missions: [
        {
          title: 'Treino Inicial',
          description: 'Complete um treino com qualquer tipo',
          experiencePoints: 100,
          goal: 1,
        },
        {
          title: 'Diversidade de Treinos',
          description: 'Complete 2 tipos de treino',
          experiencePoints: 100,
          goal: 2,
        },
        {
          title: 'Variedade de Treinos',
          description: 'Complete 3 tipos de treino',
          experiencePoints: 100,
          goal: 3,
        },
        {
          title: 'Explorando Novos Treinos',
          description: 'Complete 4 tipos de treino',
          experiencePoints: 100,
          goal: 4,
        },
        {
          title: 'Domínio de Diversos Treinos',
          description: 'Complete 5 tipos de treino',
          experiencePoints: 100,
          goal: 5,
        },
        {
          title: 'Ampliando Horizontes de Treino',
          description: 'Complete 6 tipos de treino',
          experiencePoints: 100,
          goal: 6,
        },
        {
          title: 'Especialização Multifacetada',
          description: 'Complete 7 tipos de treino',
          experiencePoints: 100,
          goal: 7,
        },
        {
          title: 'Conhecimento Abrangente de Treinos',
          description: 'Complete 8 tipos de treino',
          experiencePoints: 100,
          goal: 8,
        },
        {
          title: 'Expertise em Diferentes Tipos de Treino',
          description: 'Complete 9 tipos de treino',
          experiencePoints: 100,
          goal: 9,
        },
        {
          title: 'Mestre na Variedade de Treinos',
          description: 'Complete 10 tipos de treino',
          experiencePoints: 100,
          goal: 10,
        },
        {
          title: 'Versatilidade em Treinamentos',
          description: 'Complete 11 tipos de treino',
          experiencePoints: 200,
          goal: 11,
        },
        {
          title: 'Proficiência em Diversos Treinos',
          description: 'Complete 12 tipos de treino',
          experiencePoints: 200,
          goal: 12,
        },
        {
          title: 'Especialista em Multidisciplinaridade',
          description: 'Complete 13 tipos de treino',
          experiencePoints: 200,
          goal: 13,
        },
        {
          title: 'Mestre dos Treinos Variados',
          description: 'Complete 14 tipos de treino',
          experiencePoints: 200,
          goal: 14,
        },
        {
          title: 'Experiência Ampliada em Treinos',
          description: 'Complete 15 tipos de treino',
          experiencePoints: 200,
          goal: 15,
        },
        {
          title: 'Domínio Extensivo de Treinos',
          description: 'Complete 16 tipos de treino',
          experiencePoints: 200,
          goal: 16,
        },
        {
          title: 'Perícia em Diversos Tipos de Treino',
          description: 'Complete 17 tipos de treino',
          experiencePoints: 200,
          goal: 17,
        },
        {
          title: 'Especialização em Diversidade de Treinos',
          description: 'Complete 18 tipos de treino',
          experiencePoints: 200,
          goal: 18,
        },
        {
          title: 'Expertise em Ampla Variedade de Treinos',
          description: 'Complete 19 tipos de treino',
          experiencePoints: 200,
          goal: 19,
        },
        {
          title: 'Mestre na Multidiversidade de Treinos',
          description: 'Complete 20 tipos de treino',
          experiencePoints: 200,
          goal: 20,
        },
      ],
    },
    {
      missionType: $Enums.MissonType.REPETITION,
      missions: [
        {
          title: 'Treino Frequente',
          description: 'Realize o mesmo treino 5 vezes',
          experiencePoints: 100,
          goal: 5,
        },
        {
          title: 'Treino Repetido',
          description: 'Realize o mesmo treino 10 vezes',
          experiencePoints: 100,
          goal: 10,
        },
        {
          title: 'Treino Recorrente',
          description: 'Realize o mesmo treino 15 vezes',
          experiencePoints: 150,
          goal: 15,
        },
        {
          title: 'Treino Constante',
          description: 'Realize o mesmo treino 20 vezes',
          experiencePoints: 150,
          goal: 20,
        },
        {
          title: 'Treino Dedicado',
          description: 'Realize o mesmo treino 25 vezes',
          experiencePoints: 150,
          goal: 25,
        },
        {
          title: 'Treino Comprometido',
          description: 'Realize o mesmo treino 30 vezes',
          experiencePoints: 150,
          goal: 30,
        },
        {
          title: 'Treino Persistente',
          description: 'Realize o mesmo treino 35 vezes',
          experiencePoints: 300,
          goal: 35,
        },
        {
          title: 'Treino Incansável',
          description: 'Realize o mesmo treino 40 vezes',
          experiencePoints: 300,
          goal: 40,
        },
        {
          title: 'Treino Infatigável',
          description: 'Realize o mesmo treino 45 vezes',
          experiencePoints: 300,
          goal: 45,
        },
        {
          title: 'Treino Infinito',
          description: 'Realize o mesmo treino 50 vezes',
          experiencePoints: 300,
          goal: 50,
        },
        {
          title: 'Além do Infinito',
          description: 'Realize o mesmo treino 75 vezes',
          experiencePoints: 300,
          goal: 75,
        },
        {
          title: 'Amor infinito pelo treino',
          description: 'Realize o mesmo treino 100 vezes',
          experiencePoints: 400,
          goal: 100,
        },
        {
          title: 'Apaixonado pelo treino',
          description: 'Realize o mesmo treino 250 vezes',
          experiencePoints: 400,
          goal: 250,
        },
        {
          title: 'Mais que um treino, um estilo de vida',
          description: 'Realize o mesmo treino 500 vezes',
          experiencePoints: 500,
          goal: 500,
        },
      ],
    },
  ];

  await prisma.$transaction(
    missionsArray.flatMap((missionsTypes) =>
      missionsTypes.missions.map((mission) =>
        prisma.mission.upsert({
          create: {
            title: mission.title,
            description: mission.description,
            experiencePoints: mission.experiencePoints,
            type: missionsTypes.missionType,
            goal: mission.goal,
          },
          update: {},
          where: { title: mission.title },
        }),
      ),
    ),
  );
}
